config/routes.rb
Rails.application.routes.draw do

  resources :calendars do
    resources :events
  end

  root 'calendars#index'

  devise_for :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calendar.rb
class Calendar < ApplicationRecord
  validates_presence_of :title

  belongs_to :owner, polymorphic: true
  has_many :events, dependent: :destroy
end

app/models/calender.rb
class Calender < ApplicationRecord
  validates_presence_of :title

  belongs_to :owner, polymorphic: true
  has_many :events, dependent: :destroy
end

app/models/company.rb
class Company < ApplicationRecord
  validates_presence_of :email, :name, :phone

  has_many :calendars, as: :owner
end

app/models/event.rb
class Event < ApplicationRecord
  validates_presence_of :title, :start_time, :end_time, :color

  belongs_to :calendar
  belongs_to :user
  belongs_to :eventable, polymorphic: true, optional: true
  attr_accessor :date_range
end

app/models/interview.rb
class Interview < ApplicationRecord
  validates_presence_of :description, :interviewee, :interviewers, :methods

  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :calendars, as: :owner
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  before_action :authenticate_user!


  def index
    @calendars = current_user.calendars
  end

  def new
    @calendar = Calendar.new(owner_id: current_user.id)
  end

  def show
    @calendar = Calendar.find(params[:id])
    @events = @calendar.events
  end

  def edit
    @calendar = Calendar.find(params[:id])
  end

  def update
    @calendar = Calendar.find(params[:id])
    if @calendar.update_attributes(calendar_params)
      flash[:success] = 'Calendar updated'
      redirect_to root_url
    end
  end

  def create
    @calendar = current_user.calendars.build(calendar_params)
    if @calendar.save
      flash[:success] = 'Calendar created!'
      redirect_to root_url
    end
  end

  def destroy
    @calendar = Calendar.find(params[:id])
    @calendar.destroy
    flash[:success] = 'Calendar deleted'
  end

  private

  def calendar_params
    params.require(:calendar).permit(:title)
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, :load_calendar

  def index
    @events = @calendar.events
  end

  def new
    @event = Event.new(calendar: @calendar)
  end

  def create
    @event = @calendar.events.build event_params
    @event.user = current_user
    date_conversion()
    @event.save
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @calendar = current_user.calendars.find params[:calendar_id]
    @event = @calendar.events.find(params[:id])
  end

  def update
    @event = @calendar.events.find(params[:id])
    if @event.update_attributes(event_params)
      flash[:success] = 'Event updated'
    else
      flash[:error] = @event.errors.full_messages
      redirect_to edit_calendar_event_path(@calendar)
    end
  end

  def destroy
    @event = @calendar.events.find(params[:id])
    @event.destroy
    flash[:success] = 'Event deleted'
  end

  private

  def load_calendar
    @calendar = current_user.calendars.find params[:calendar_id]
  end

  def event_params
    params.require(:event).permit(:title, :start_time, :end_time, :color, :date_range)
  end

  def date_conversion
    start_time = params[:event][:start_time].split(' ')
    end_time = params[:event][:end_time].split(' ')
    date = params[:event][:date_range]
    str = date + ' ' + start_time[1]
    str2 = date + ' ' + end_time[1]
    @event.start_time = DateTime.strptime( str, '%m/%d/%Y %H:%M')
    @event.end_time = DateTime.strptime( str2, '%m/%d/%Y %H:%M')
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/calendars/_calendar.html.erb
<li id="calendar-<%= calendar.id %>">
  <span class="content">
    <%= calendar.title %>
    <%= calendar.owner_type %>
    <%= calendar.owner_id %>
  </span>
  <span>
      <%= link_to 'delete', calendar, method: :delete,
                  data: { confirm: 'You sure?'} %>
  </span>
  <span>
      <%= link_to 'edit', edit_calendar_path(calendar.id) %>
  </span>
  <span>
    <%= link_to 'show calendar', calendar_path(calendar.id) %>
  </span>

</li>

app/views/calendars/_form.html.erb
<%= form_with model: @calendar do |f| %>
    <div class="field">
      <%= f.text_area :title, placeholder: 'Compose new Calendar' %>
    </div>
    <%= f.submit 'Post', class: 'btn btn-primary' %>
<% end %>

app/views/calendars/edit.html.erb
<h1>Update your Calendar</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with model: @calendar do |f| %>

        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
        <%= f.submit 'Save changes', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/calendars/index.html.erb
<div class="row">

  <div class="col-md-12">
    <ol>
      <%= render @calendars %>
    </ol>
  </div>

</div>

app/views/calendars/new.html.erb
<div class="row">
  <aside class="col-md-4">

    <section>
      <%= render 'form' %>
    </section>

  </aside>
  <span>
    <li><%= link_to 'show', calendars_path %></li>

  </span>

</div>

app/views/calendars/show.html.erb
<h3 class="calendar_name">
    <%= @calendar.title %>
</h3>
<div id='calendar'></div>
<div id='remote_container'></div>

app/views/calenders/edit.html.erb
<h1>Update your Calender</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@calender) do |f| %>

        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
        <%= f.submit 'Save changes', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/calenders/index.html.erb
<div class="row">

  <div class="col-md-12">
        <ol>
          <%= render @calenders %>
        </ol>
  </div>

</div>

<div class="row">
  <aside class="col-md-4">

    <section>
      <%= render 'shared/calender_form' %>
    </section>

  </aside>
  <span>
    <li><%= link_to 'show', calenders_path %></li>
  </span>

</div>

app/views/events/_edit.html.erb
<div class="modal fade" id="edit_event">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Edit Event</h4>
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      </div>
      <div class="modal-body">
        <%= render 'form', event: @event %>
      </div>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<div >
  <div class="col-md-auto">
    <%= form_with model: [@calendar,@event], id: 'form' do |f| %>
        <div class="errors"></div>
        <div class="form-inputs">
          <%= f.text_field :title, placeholder: 'Title'%>
          <%= f.text_field :date_range, class: 'form-control input-sm start-range-picker' %>
          <%= f.text_field :time_range, class: 'form-control input-sm end-range-picker' %>
          <%= f.hidden_field :start_time, class: 'form-control input-sm start_hidden' %>
          <%= f.hidden_field :end_time, class: 'form-control input-sm end_hidden' %>
          <%= f.select :color, [%w(Black black), %w(Green green), %w(Red red)], {:include_blank => 'Choose Color' }, :required => true, class:'btn btn-info btn-sm dropdown-toggle dropdown-toggle-split'%>

        </div>
        <div class="form-actions">
          <%= f.button :submit, id: 'submit',class: 'btn btn-info btn-sm extra-padding' %>
          <%= link_to 'Delete',
                      calendar_event_path(@calendar, event),
                      method: :delete,
                      data: { confirm: 'Are you sure?' },
                      remote: true unless @event.new_record? %>
        </div>
    <% end %>
  </div>
</div>

app/views/events/_new.html.erb
<div class="modal fade" id="new_event">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Create New Event</h4>
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      </div>
      <div class="modal-body">
        <%= render 'form', event: @event %>
      </div>
    </div>
  </div>
</div>

app/views/events/create.js.erb
console.log($.parseJSON("<%=j render(@event, format: :json).html_safe %>"))
window.calendar.addEvent(
    $.parseJSON("<%=j render(@event, format: :json).html_safe %>")
);
$('.modal').modal('hide');

app/views/events/destroy.js.erb
window.calendar.getEventById(<%= @event.id %>).remove();
$('.modal').modal('hide');

app/views/events/edit.js.erb
$('#remote_container').html('<%= j render 'edit' %>');
$('#edit_event').modal('show');

app/views/events/new.js.erb
$('#remote_container').html('<%= j render 'new' %>');
$('#new_event').modal('show');

app/views/events/show.html.erb
<li>
  <span class="content">
    <%= @event.title %>
    <%= @event.start_time %>
    <%= @event.end_time %>
    <%= @event.repeat %>
    <%= @event.repeat_value %>
    <%= @event.repeat_type %>


 </span>
</li>

app/views/events/update.js.erb
window.calendar.getEventById(<%= @event.id %>).remove();
window.calendar.addEvent(
  $.parseJSON("<%=j render(@event, format: :json).html_safe %>")
);
$('.modal').modal('hide');

app/views/layouts/_footer.html.erb
<footer class="page-footer font-small navbar-fixed-bottom extra-ft">
  <div class="footer-copyright text-center py-3 extra-ft-div">© 2018 Copyright:
    <a class="extra-ft-a" href="http://www.nextbridge.pk/"> NextBridge</a>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class='navbar navbar-light navbar-fixed-top navbar-inverse' style='background-color: #138496;' >
  <div class='container'>
    <%= link_to 'Schedular', root_url, id: 'logo' %>
    <nav>
      <ul class='nav navbar-nav navbar-right' class = 'extra-color-lf'>
        <li class = 'extra-color-lf'><%= link_to 'Home', root_url %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Schedular</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class='container'>
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_calendar_form.html.erb
<%= form_for(@calendar) do |f| %>
    <div class="field">
      <%= f.text_area :title, placeholder: 'Compose new Calendar' %>
    </div>
    <%= f.submit 'Post', class: 'btn btn-primary' %>
<% end %>